language: objective-c
osx_image: xcode9.2
xcode_workspace: Fermentor.xcworkspace
xcode_scheme: Fermentor
script: xcodebuild -workspace Fermentor.xcworkspace -scheme Fermentor -sdk iphonesimulator7.1 -configuration Debug build test
